## 5.1.1 Series

In [2]:
import pandas as pd
from pandas import Series, DataFrame

In [3]:
obj = Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4,7,-5,3], index = ['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2['a']

-5

In [10]:
obj2['d']

4

In [11]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [12]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [14]:
import numpy as np

In [15]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
sdata ={'Ohio': 35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [19]:
obj3 = Series(sdata)

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = Series(sdata, index = states)

In [23]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [25]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
obj3 + obj4 

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [29]:
obj4.name = 'population'

In [30]:
obj4.index.name = 'state'

In [31]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [32]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [33]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## 5.1.2 DataFrame

In [34]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year' : [2000, 2001, 2002, 2001, 2002],
       'pop' : [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [35]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [36]:
DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [37]:
frame2 = DataFrame(data, columns = ['year','state','pop','debt'],
                  index = ['one','two','three','four','five'])

In [38]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [39]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [40]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [41]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [42]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [43]:
frame2['debt'] = 16.5

In [44]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [45]:
frame2['debt'] = np.arange(5.)

In [46]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [47]:
val = Series([-1.2 , -1.5, -1.7], index = ['two','four','five'])

In [48]:
frame2['debt'] = val

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [50]:
frame2['eastern'] = frame2.state == 'Ohio'

In [51]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [52]:
del frame2['eastern']

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [54]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001:1.7, 2002: 3.6}}

In [55]:
frame3 = DataFrame(pop)

In [56]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [57]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [58]:
DataFrame(pop, index =[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [59]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Neada': frame3['Nevada'][:2]}

In [60]:
DataFrame(pdata)

Ohio  Neada
2001   1.7    2.4
2002   3.6    2.9

In [61]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [62]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [63]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [64]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

## 5.1.3 index object

In [65]:
obj = Series(range(3), index=['a','b','c'])

In [66]:
index = obj.index

In [67]:
index

Index(['a', 'b', 'c'], dtype='object')

In [68]:
index[1:]

Index(['b', 'c'], dtype='object')

In [69]:
index = pd.Index(np.arange(3))

In [70]:
obj2 = Series([1.5, -2.5, 0], index = index)

In [71]:
obj2.index is index

True

In [72]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [73]:
'Ohio' in frame3.columns

True

In [74]:
2003 in frame3.index

False

## 5.1.2 Reindex

In [75]:
obj = Series([4.5, 7.2, -5.3, 3.6], index = ['d','b','a','c'])

In [76]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [77]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [78]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [79]:
obj.reindex(['a','b','c','d','e'], fill_value = 0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [80]:
obj3 = Series(['blue','purple','yellow'], index = [0,2,4])

In [81]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [82]:
frame = DataFrame(np.arange(9).reshape((3,3)), index = ['a','c','d'], columns = ['Ohio','Texas','California'])

In [83]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [84]:
frame2 = frame.reindex(['a','b','c','d'])

In [85]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [86]:
states = ['Texas', 'Utah', 'California']

In [87]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [88]:
frame.reindex(index = ['a','b','c','d'], columns = states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [89]:
states = ['Texas', 'Ohio', 'California']

In [90]:
ranger = ['a','b','c','d']
frame.reindex(ranger, columns = states).ffill()

Texas  Ohio  California
a    1.0   0.0         2.0
b    1.0   0.0         2.0
c    4.0   3.0         5.0
d    7.0   6.0         8.0

## 5.2.2  하나의 로우 또는 칼럼 삭제

In [91]:
obj = Series(np.arange(5.), index = ['a','b','c','d','e'])

In [92]:
new_obj = obj.drop('c')

In [93]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [94]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [95]:
data = DataFrame(np.arange(16).reshape((4,4)),
                index = ['Ohio','Colorado','Utah','New York'],
                columns = ['one','two','three','four'])

In [96]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [97]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
data.drop('Ohio',axis = 0)

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [100]:
data.drop(['two','four'], axis =1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## 5.2.3  색인하기, 선택하기, 거르기

In [101]:
obj = Series(np.arange(4.), index=['a','b','c','d'])

In [102]:
obj['b']

1.0

In [103]:
obj[1]

1.0

In [104]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [105]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [106]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [107]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [108]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [109]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [110]:
obj['b':'c'] = 5

In [111]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [112]:
data = DataFrame(np.arange(16).reshape((4,4)),
                index = ['Ohio','Colorado','Utah','New York'],
                columns = ['one','two','three','four'])

In [113]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [115]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [116]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [117]:
data[data < 5] = 0

In [118]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## 5.2.4 산술연산과 데이터 정렬

In [119]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index= ['a','c','d','e'])

In [120]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [121]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a','c','e','f','g'])

In [122]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [123]:
s1+ s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [124]:
df1 = DataFrame(np.arange(9.).reshape((3,3)), columns = list('bcd'), index = ['Ohio','Texas','Colorado'])

In [125]:
df2 = DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'), index = ['Utah','Ohio','Texas','Oregon'])

In [126]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [127]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [128]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [129]:
df3 = DataFrame(np.arange(9.).reshape((3,3)), columns = list('bde'), index = ['Ohio','Texas','Colorado'])

In [130]:
df3

b    d    e
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [131]:
df1+df3

b   c     d   e
Ohio       0.0 NaN   3.0 NaN
Texas      6.0 NaN   9.0 NaN
Colorado  12.0 NaN  15.0 NaN

In [132]:
df1.add(df3, fill_value = 0)

b    c     d    e
Ohio       0.0  1.0   3.0  2.0
Texas      6.0  4.0   9.0  5.0
Colorado  12.0  7.0  15.0  8.0

In [133]:
df2+df3

b     d     e
Colorado  NaN   NaN   NaN
Ohio      3.0   5.0   7.0
Oregon    NaN   NaN   NaN
Texas     9.0  11.0  13.0
Utah      NaN   NaN   NaN

In [134]:
df2.add(df3, fill_value = 0)

b     d     e
Colorado  6.0   7.0   8.0
Ohio      3.0   5.0   7.0
Oregon    9.0  10.0  11.0
Texas     9.0  11.0  13.0
Utah      0.0   1.0   2.0

In [135]:
df1.add(df2, fill_value = 0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [136]:
arr = np.arange(12.).reshape((3,4))

In [137]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [138]:
arr[0]

array([0., 1., 2., 3.])

In [139]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [140]:
frame = DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'),
                 index = ['Utah','Ohio','Texas','Oregon'])

In [141]:
series = frame.iloc[0]

In [142]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [143]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [144]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [145]:
series2 = Series(range(3), index = ['b','e','f'])

In [146]:
series2

b    0
e    1
f    2
dtype: int64

In [147]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [148]:
series3 = frame['d']

In [149]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [150]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [151]:
frame.sub(series3, axis = 0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 5.2.5 함수 적용과 매핑

In [152]:
frame = DataFrame(np.random.randn(4,3), columns = list('bde'),
                 index = ['Utah','Ohio','Texas','Oregon'])

In [153]:
frame

b         d         e
Utah    0.567608 -0.583397  0.561210
Ohio   -0.357107 -1.166700  0.103113
Texas  -0.786888 -1.578879  0.544961
Oregon -0.910215 -0.605191  0.574056

In [154]:
np.abs(frame)

b         d         e
Utah    0.567608  0.583397  0.561210
Ohio    0.357107  1.166700  0.103113
Texas   0.786888  1.578879  0.544961
Oregon  0.910215  0.605191  0.574056

In [155]:
f = lambda x: x.max() - x.min()

In [156]:
frame.apply(f)

b    1.477822
d    0.995482
e    0.470943
dtype: float64

In [157]:
frame.apply(f, axis = 1)

Utah      1.151005
Ohio      1.269813
Texas     2.123840
Oregon    1.484270
dtype: float64

In [158]:
def f(x):
    return Series([x.min(), x.max()], index = ['min','max'])

In [159]:
frame.apply(f)

b         d         e
min -0.910215 -1.578879  0.103113
max  0.567608 -0.583397  0.574056

In [160]:
format = lambda x: '%.2f' %x

In [161]:
frame.applymap(format)

b      d     e
Utah     0.57  -0.58  0.56
Ohio    -0.36  -1.17  0.10
Texas   -0.79  -1.58  0.54
Oregon  -0.91  -0.61  0.57

In [162]:
frame['e'].map(format)

Utah      0.56
Ohio      0.10
Texas     0.54
Oregon    0.57
Name: e, dtype: object

## 5.2.6 정렬과 순위

In [163]:
obj = Series(range(4), index = ['d','a','b','c'])

In [164]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [165]:
frame = DataFrame(np.arange(8).reshape((2,4)), index = ['three','one'],
                 columns = ['d','a','b','c'])

In [166]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [167]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [168]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [169]:
obj = Series([4,7,-3,2])

In [170]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [171]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])

In [172]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [173]:
frame = DataFrame({'b': [4,7,-3,2], 'a': [0,1,0,1]})

In [174]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [175]:
frame.sort_index(axis = 1)

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [176]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [177]:
frame.sort_values(by = 'a')

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [178]:
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [179]:
obj = Series([7,-5,7,4,2,0,4])

In [180]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [181]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [182]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [183]:
frame = DataFrame({'a':[0,1,0,1],'b':[4.3,7,-3,2],
                  'c':[-2,5,8,-2.5]})

In [184]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [185]:
frame.rank(axis = 1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

## 5.2.7 중복 색인

In [186]:
obj = Series(range(5), index = ['a','a','b','b','c'])

In [187]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [188]:
obj.index.is_unique

False

In [189]:
obj['a']

a    0
a    1
dtype: int64

In [190]:
obj['c']

4

In [191]:
df = DataFrame(np.random.randn(4,3), index = ['a','a','b','b'])

In [192]:
df

0         1         2
a  0.500992  0.575792  0.416778
a -0.102219  1.155090 -1.073369
b -0.861813  0.006349  0.167998
b -1.873447  0.724474 -1.670922

In [193]:
df.loc['b']

0         1         2
b -0.861813  0.006349  0.167998
b -1.873447  0.724474 -1.670922

## 5.3 기술통계 계산과 요약

In [194]:
df = DataFrame([[1.4,np.nan],[7.1, -4.5],
               [np.nan,np.nan], [0.75, -1.3]],
               index = ['a','b','c','d'],
               columns = ['one','two'])

In [195]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [196]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [197]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [198]:
df.mean(axis=1, skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [199]:
df.idxmax()

one    b
two    d
dtype: object

In [200]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [201]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [202]:
obj = Series(['a','a','b','c']*4)

In [203]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### 5.3.1 상관관계와 공분산

In [204]:
!pip install pandas-datareader

In [205]:
# from pandas_datareader import data, wb

In [206]:
import pandas_datareader.data as web #import pandas.io.data as web 버전 문제로 호환 안 됨

In [207]:
all_data = {}
for ticker in ['AAPL','IBM','MSFT','GOOG']:
    all_data[ticker] = web.get_data_yahoo(ticker, '1/1/2000', '1/1/2010')


In [208]:
all_data

{'AAPL':                 High       Low      Open     Close       Volume  Adj Close
 Date                                                                      
 1999-12-31  0.918527  0.888393  0.901228  0.917969  163811200.0   0.791887
 2000-01-03  1.004464  0.907924  0.936384  0.999442  535796800.0   0.862169
 2000-01-04  0.987723  0.903460  0.966518  0.915179  512377600.0   0.789480
 2000-01-05  0.987165  0.919643  0.926339  0.928571  778321600.0   0.801032
 2000-01-06  0.955357  0.848214  0.947545  0.848214  767972800.0   0.731712
 ...              ...       ...       ...       ...          ...        ...
 2009-12-24  7.476786  7.262500  7.269643  7.465714  500889200.0   6.440303
 2009-12-28  7.641071  7.486071  7.561429  7.557500  644565600.0   6.519482
 2009-12-29  7.597143  7.454643  7.593929  7.467857  445205600.0   6.442152
 2009-12-30  7.571429  7.439643  7.458214  7.558571  412084400.0   6.520405
 2009-12-31  7.619643  7.520000  7.611786  7.526071  352410800.0   6.492369
 
 [

In [209]:
price = DataFrame({tic: data['Adj Close']
                  for tic, data in all_data.items()})
volume = DataFrame({tic: data['Volume']
                   for tic, data in all_data.items()})

In [210]:
returns = price.pct_change()

In [211]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2009-12-24  0.034340  0.004385  0.002587  0.011117
2009-12-28  0.012294  0.013326  0.005484  0.007098
2009-12-29 -0.011861 -0.003477  0.007058 -0.005571
2009-12-30  0.012147  0.005461 -0.013699  0.005376
2009-12-31 -0.004300 -0.012597 -0.015504 -0.004416

In [212]:
returns.MSFT.corr(returns.IBM)

0.49435840887788896

In [213]:
returns.MSFT.cov(returns.IBM)

0.00021582142565483846

In [214]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.412391  0.423598  0.470676
IBM   0.412391  1.000000  0.494358  0.390689
MSFT  0.423598  0.494358  1.000000  0.443586
GOOG  0.470676  0.390689  0.443586  1.000000

In [215]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.001030  0.000254  0.000309  0.000303
IBM   0.000254  0.000369  0.000216  0.000142
MSFT  0.000309  0.000216  0.000516  0.000205
GOOG  0.000303  0.000142  0.000205  0.000580

In [216]:
returns.corrwith(returns.IBM)

AAPL    0.412391
IBM     1.000000
MSFT    0.494358
GOOG    0.390689
dtype: float64

In [217]:
returns.corrwith(volume)

AAPL   -0.057665
IBM    -0.006592
MSFT   -0.014228
GOOG    0.062648
dtype: float64

### 5.3.2 유일 값, 값 세기, 멤버십

In [218]:
obj = Series(['c','a','d','a','a','b','b','c,','c'])

In [219]:
uniques = obj.unique()

In [220]:
uniques

array(['c', 'a', 'd', 'b', 'c,'], dtype=object)

In [221]:
obj.value_counts()

a     3
b     2
c     2
d     1
c,    1
dtype: int64

In [222]:
pd.value_counts(obj.values, sort = False)

c     2
c,    1
d     1
b     2
a     3
dtype: int64

In [223]:
mask = obj.isin(['b','c'])

In [224]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7    False
8     True
dtype: bool

In [225]:
obj[mask]

0    c
5    b
6    b
8    c
dtype: object

In [226]:
data = DataFrame({'Qu1': [1,3,4,3,4],
                 'Qu2': [2,3,1,2,3],
                 'Qu3': [1,5,2,4,4]})

In [227]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [228]:
result = data.apply(pd.value_counts).fillna(0)

In [229]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

## 5.4 누락데이터 처리

In [230]:
string_data = Series(['aaardvark','artichoke', np.nan, 'avocado'])

In [231]:
string_data

0    aaardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [232]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [233]:
string_data[0] = None

In [234]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

## 5.4.1 누락된 데이터 고르기

In [235]:
from numpy import nan as NA

In [236]:
data = Series([1, NA, 3.5, NA, 7])

In [237]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [238]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [239]:
data = DataFrame([[1., 6.5, 3.],[1., NA,NA],
                 [NA,NA,NA], [NA, 6.5, 3.]])

In [240]:
cleaned = data.dropna()

In [241]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [242]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [243]:
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [244]:
data[4] = NA

In [246]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [247]:
data.dropna(axis =1, how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [248]:
df = DataFrame(np.random.randn(7,3))

In [250]:
df.loc[:4,1] = NA

In [251]:
df.loc[:2,2] = NA

In [252]:
df

0         1         2
0  1.420629       NaN       NaN
1 -0.017088       NaN       NaN
2 -2.596299       NaN       NaN
3  0.173125       NaN  0.875897
4  0.245188       NaN -1.622316
5  1.579320  0.176901  0.030277
6  0.525705  1.332348 -0.537007

In [253]:
df.dropna(thresh = 3)

0         1         2
5  1.579320  0.176901  0.030277
6  0.525705  1.332348 -0.537007

In [254]:
df.fillna(0)

0         1         2
0  1.420629  0.000000  0.000000
1 -0.017088  0.000000  0.000000
2 -2.596299  0.000000  0.000000
3  0.173125  0.000000  0.875897
4  0.245188  0.000000 -1.622316
5  1.579320  0.176901  0.030277
6  0.525705  1.332348 -0.537007

In [255]:
df.fillna({1: 0.5, 3: -1})

0         1         2
0  1.420629  0.500000       NaN
1 -0.017088  0.500000       NaN
2 -2.596299  0.500000       NaN
3  0.173125  0.500000  0.875897
4  0.245188  0.500000 -1.622316
5  1.579320  0.176901  0.030277
6  0.525705  1.332348 -0.537007

In [256]:
df.fillna(0, inplace = True)

In [257]:
df

0         1         2
0  1.420629  0.000000  0.000000
1 -0.017088  0.000000  0.000000
2 -2.596299  0.000000  0.000000
3  0.173125  0.000000  0.875897
4  0.245188  0.000000 -1.622316
5  1.579320  0.176901  0.030277
6  0.525705  1.332348 -0.537007

In [259]:
df.fillna(3, inplace = True)

In [260]:
df

0         1         2
0  1.420629  0.000000  0.000000
1 -0.017088  0.000000  0.000000
2 -2.596299  0.000000  0.000000
3  0.173125  0.000000  0.875897
4  0.245188  0.000000 -1.622316
5  1.579320  0.176901  0.030277
6  0.525705  1.332348 -0.537007

In [262]:
df = DataFrame(np.random.randn(6,3))

In [263]:
df.loc[2:,1] = NA

In [264]:
df.loc[4:, 2] = NA

In [265]:
df

0         1         2
0  1.004593  0.633753  0.862535
1 -0.772109 -0.084071  2.602053
2 -0.298278       NaN  0.134063
3 -2.085700       NaN -2.361953
4 -0.878441       NaN       NaN
5  2.158018       NaN       NaN

In [266]:
data = Series([1., NA, 3.5, NA, 7])

In [267]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [269]:
data = Series(np.random.randn(10),
             index = [['a','a','a','b','b','b','c','c','d','d'],
                     [1,2,3,1,2,3,1,2,2,3]])

In [270]:
data

a  1    1.146882
   2   -0.135637
   3    0.207119
b  1   -0.030060
   2    1.375701
   3    0.761378
c  1   -0.392017
   2    0.917639
d  2   -2.240292
   3   -2.789254
dtype: float64

In [271]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [272]:
data['b']

1   -0.030060
2    1.375701
3    0.761378
dtype: float64

In [273]:
data['b':'c']

b  1   -0.030060
   2    1.375701
   3    0.761378
c  1   -0.392017
   2    0.917639
dtype: float64

In [275]:
data[:,2]

a   -0.135637
b    1.375701
c    0.917639
d   -2.240292
dtype: float64

In [280]:
data.unstack()

1         2         3
a  1.146882 -0.135637  0.207119
b -0.030060  1.375701  0.761378
c -0.392017  0.917639       NaN
d       NaN -2.240292 -2.789254

In [281]:
data.unstack().stack()

a  1    1.146882
   2   -0.135637
   3    0.207119
b  1   -0.030060
   2    1.375701
   3    0.761378
c  1   -0.392017
   2    0.917639
d  2   -2.240292
   3   -2.789254
dtype: float64

In [ ]:
df.loc

In [ ]:
df.

In [245]:
frame.index.is_unique

True